-- restaurar bd
-- restaurar logins EXEC sp_change_users_login 'Update_one','adm_obj_db','adm_obj_db'
-
use seguridad
go
EXEC sp_change_users_login 'Update_one','SOFT','SOFT'
EXEC sp_change_users_login 'Update_one','RPT','RPT'
go
use transacmif
go
EXEC sp_change_users_login 'Update_one','SOFT','SOFT'
EXEC sp_change_users_login 'Update_one','RPT','RPT'
go
use contabmif
go
EXEC sp_change_users_login 'Update_one','SOFT','SOFT'
EXEC sp_change_users_login 'Update_one','RPT','RPT'
go

USE TRANSACMIF
DELETE TRABAJO
DELETE TMP_ASIENTOCARTERA
DELETE TMP_CUOTAS
DELETE TMP_HOJADECOLECTA
DELETE TMP_MES
DELETE TMP_ARREGLA_AHORROS
DELETE SOLIRENUNCIA

DELETE SOLIDARIO
DELETE SOLI_APRUEBA

DELETE REPORT
DELETE PROCESOS

DELETE MOVVAR
DELETE MOVREM
DELETE MOVPRE
DELETE MOVI_MONETEO
DELETE MOVCXC
DELETE MOVCUOTAS
DELETE MOVAHO
DELETE MONETEO
DELETE LEGAJO_SOCIO
DELETE INTERPLAZO
DELETE HISTORICO_CUOTAS
DELETE HISTORICO_CAPITALIZACION
DELETE FIRMAS
DELETE FAMILIA
DELETE EVALUA_ECONOMICA
DELETE DOCUMENTO
DELETE DIRECCION
DELETE DETALLE_SOLIDARIO
DELETE DEDUCESOLI
DELETE CXCOB
DELETE CUOTAS
DELETE CONTROLASIENTO
DELETE CONTROL_REPROG
DELETE CONTROL_APORTE
DELETE CARTERARECUP
DELETE CARTERANALISTA
DELETE CARTERA
DELETE BENEFICIARIO
DELETE AVALSOCIO
DELETE ARQUEO
DELETE AHORRO
DELETE TIPO_CAMBIO
----
  DELETE GARANTE
  DELETE PRESTAMO
  DELETE SOLIPRESTA
  DELETE SOCIOS
  DELETE NUM_TRANSAC
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '01', '01', 0, NULL, '2010-01-04 17:05:24')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '01', '02', 0, NULL, '2010-01-04 17:05:23')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '01', '03', 0, NULL, '2010-01-18 19:36:02')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '01', '05', 0, NULL, '2010-01-08 11:29:59')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '01', '06', 0, NULL, '2010-01-04 10:45:49')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '20', '01', 0, NULL, '2010-01-21 19:22:18')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '20', '05', 0, NULL, '2010-01-31 09:39:03')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '20', '06', 0, NULL, '2010-01-04 10:45:47')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '24', '01', 0, NULL, '2010-01-05 17:22:46')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '24', '02', 0, NULL, '2010-01-05 17:22:46')
GO
INSERT INTO NUM_TRANSAC (PERIODO, COD_COOP, COD_AGE, COD_CAJA, TABLA_MOV, CONTADOR, ANULADOS, DATE_UPD) 
VALUES ('2010', '514', '01', '24', '03', 0, NULL, '2010-01-05 17:22:46')
GO


--?revisar las  fechas
SELECT * FROM NUMAHORRO
DELETE NUMAHORRO
INSERT INTO NUMAHORRO (COD_COOP, COD_AGE, TIPO_AHO, SUBTIPO_AHO, CONTADOR) VALUES ('514', '01', '03', '201', 0)
GO
INSERT INTO NUMAHORRO (COD_COOP, COD_AGE, TIPO_AHO, SUBTIPO_AHO, CONTADOR) VALUES ('514', '01', '03', '101', 0)
GO
INSERT INTO NUMAHORRO (COD_COOP, COD_AGE, TIPO_AHO, SUBTIPO_AHO, CONTADOR) VALUES ('514', '01', '02', '101', 0)
GO


SELECT * FROM NUM_DOCUM
DELETE NUM_DOCUM WHERE PERIODO<>'2010'
UPDATE NUM_DOCUM  SET CONTADOR=0 ,COD_COOP='514' , COD_AGE='01'


USE SEGURIDAD
UPDATE COOPAC SET COD_COOP='514' 
UPDATE CAJEROS SET COD_COOP='514' , COD_AGE='01'
UPDATE ACCESO SET COD_COOP='514' , COD_AGE='01'
UPDATE AGENCIA SET COD_COOP='514' 
UPDATE AGENCIA SET COD_AGE='01' WHERE NOM_AGE='OFICINA PRINCIPAL' 
UPDATE ANALISTA SET COD_COOP='514' , COD_AGE='01'
DELETE CONTROLSISTEMA
UPDATE POLITICA_AHORRO SET COD_COOP='514' 
UPDATE POLITICA_CREDITOS SET COD_COOP='514' 
UPDATE RECUPERADOR SET COD_COOP='514' , COD_AGE='01'
DELETE REGISTRO_INGRESO



-------------------------------------------------------------


--copiar un registro y luego actualizar manualmente con los paramentros
 select* from controlsistema
 delete controlsistema
INSERT INTO dbo.CONTROLSISTEMA (COOPAC, AGENCIA, FEC_APE, USER_APE, PC_NAME_APE, IP_APE, FECHA_CIERRE, USER_CIERRE, PC_NAME_CIERRE, IP_CIERRE, ESTADO)
VALUES ('514', '1', '20100630', 'CGRAL03', 'SERVIDOR', '192.168.1.50', '20100630', 'CGRAL03', 'SERVIDOR', '192.168.1.50', 'C')
GO

--copiar un registro y luego actualizar manualmente con los paramentros
--capitalizacion del mes anterior
use TRANSACMIF

select * from procesos
delete procesos
--  cod_proceso descripcion
-- 	01	PLAZO FIJO
-- 	02	CAPITALIZACION
-- 	03	APORTACIONES
-- 	04	CIERRE DE CARTERA
-- 	05	PREVISION SOCIAL
--plazo fijo
INSERT INTO PROCESOS (COD_COOP, COD_AGE, COD_PROCESO, PERIODO, MES, DIA, COD_USER, HORA) 
VALUES ('514', '01', '01', '2010', '06', '30', 'CGRAL03', NULL)
GO
--capitalizacion
INSERT INTO PROCESOS (COD_COOP, COD_AGE, COD_PROCESO, PERIODO, MES, DIA, COD_USER, HORA) 
VALUES ('514', '01', '02', '2010', '06', '30', 'CGRAL03', NULL)
GO
--aportaciones
INSERT INTO PROCESOS (COD_COOP, COD_AGE, COD_PROCESO, PERIODO, MES, DIA, COD_USER, HORA) 
VALUES ('514', '01', '03', '2010', '06', '30', 'CGRAL03', NULL)
GO

--cierre de cartera
INSERT INTO PROCESOS (COD_COOP, COD_AGE, COD_PROCESO, PERIODO, MES, DIA, COD_USER, HORA) 
VALUES ('514', '01', '04', '2010', '06', '30', 'CGRAL03', NULL)
GO

--prevision social
INSERT INTO PROCESOS (COD_COOP, COD_AGE, COD_PROCESO, PERIODO, MES, DIA, COD_USER, HORA) 
VALUES ('514', '01', '05', '2010', '06', '30', 'CGRAL03', NULL)
GO

--apertura cajeros verificar que tenga cero de saldo
-- tipo de cambio

--------------------------------------------------------------

select * from tasasprestamo

update tasasprestamo set cod_age='01'
go
select * from controlcajas
delete controlcajas  
INSERT INTO CONTROLCAJAS (FECHA_MOV, COD_COOP, COD_AGE, COD_CAJA, ESTADO, USER_DCAJA, USER_APER, FECHA_CIERRE, USER_CIERRE, HORA_APERTURA) 
VALUES ('20100630', '500', '01', '01', 'C', 'CAJA03', '', '20100630', 'CAJA03', '20100630')
GO
INSERT INTO CONTROLCAJAS (FECHA_MOV, COD_COOP, COD_AGE, COD_CAJA, ESTADO, USER_DCAJA, USER_APER, FECHA_CIERRE, USER_CIERRE, HORA_APERTURA) 
VALUES ('20100630', '500', '01', '20', 'C', 'CGRAL03', '', '20100630', '', '20100630')
GO

select * from nivelaprobacion
UPDATE NIVELAPROBACION SET COD_AGE='01'
go
select * from sector
DELETE sector 
 select * from tabla_apo
 delete tabla_apo
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '01', 10, 0, 0, 5, 10, 10, 10, 35, 'CGRAL03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '02', 10, 0, 0, 5, 10, 10, 10, 35, 'CGRAL03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '03', 10, 0, 0, 5, 10, 10, 10, 35, 'CGRAL03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '04', 10, 0, 0, 5, 10, 10, 10, 35, 'CGRAL03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '05', 10, 0, 0, 5, 10, 10, 10, 35, 'CGRAL03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '06', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '07', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '08', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '09', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '10', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '11', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO
INSERT INTO TABLA_APO (PERIODO, MES, CUOTA_APORTE_MN, CUOTA_APORTE_ME, CUOTA_APORTE_NINO, CUOTA_INGRESO, CUOTA_FPS_SOCIO, CUOTA_FPS_NINO, CUOTA_FPS_CONYUGE, APORTE_INSCRIPCION, COD_USUARIO, DATE_ACTUALIZA) 
VALUES ('2010', '12', 10, 0, 0, 5, 10, 10, 10, 35, 'ADMIN03', NULL)
GO

--cuando hay error de no se hizo proceso de capitalizacion o proceso de cierre de cartera
-- agregar registro en la tabla procesos


